import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        display: ['"Playfair Display"', "serif"],
        sans: [
          "Geist",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        body: ["Inter", "system-ui", "sans-serif"],
        mono: [
          '"Geist Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        canvas: "rgb(var(--canvas-rgb) / <alpha-value>)",
        pad: "rgb(var(--pad-rgb) / <alpha-value>)",
        card: "rgb(var(--card-rgb) / <alpha-value>)",
        "card-cream": "rgb(var(--card-cream-rgb) / <alpha-value>)",
        inverse: "rgb(var(--inverse-rgb) / <alpha-value>)",
        "inverse-alt": "rgb(var(--inverse-alt-rgb) / <alpha-value>)",
        "on-inverse": "rgb(var(--on-inverse-rgb) / <alpha-value>)",
        ink: "rgb(var(--ink-rgb) / <alpha-value>)",
        "ink-alt": "rgb(var(--inverse-alt-rgb) / <alpha-value>)",
        body: "rgb(var(--body-rgb) / <alpha-value>)",
        muted: "rgb(var(--muted-rgb) / <alpha-value>)",
        caption: "rgb(var(--caption-rgb) / <alpha-value>)",
        accent: "rgb(var(--accent-rgb) / <alpha-value>)",
        conflict: "#7F1D1D",
        danger: "#B23A3A",
        "danger-soft": "#B4301F",
        hairline: "var(--hairline)",
        layer: {
          managed: "#7C5CE0",
          user: "#6BA3FF",
          "user-local": "#2DB3A0",
          project: "#D97A37",
          "project-local": "#C45183",
        },
      },
      borderRadius: {
        "soft-sm": "10px",
        "soft-md": "12px",
        "soft-lg": "16px",
        "soft-xl": "20px",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        lift: "var(--shadow-lift)",
        "focus-ink": "var(--shadow-focus-ink)",
      },
    },
  },
  plugins: [],
} satisfies Config;
